export type { MockProduct, MockVariant, Product, ProductVariant } from './types';

import type { Product } from './types';

export const mockProducts: Product[] = [
  {
    _id: 'prod-1',
    slug: 'extension-lisse-naturelle',
    name: 'Extension Lisse Naturelle',
    shortDescription: 'Extensions 100% Remy, texture lisse parfaite',
    basePrice: 890,
    comparePrice: 1100,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    stockStatus: 'in_stock',
    productType: ['extensions'],
    texture: ['lisse'],
    rating: 4.8,
    reviewCount: 124,
    variants: [
      { _key: 'v1a', label: '40cm - Noir Naturel', color: { name: 'Noir Naturel', hexCode: '#1A1410' }, length: 40, price: 890, stock: 15, isAvailable: true },
      { _key: 'v1b', label: '50cm - Noir Naturel', color: { name: 'Noir Naturel', hexCode: '#1A1410' }, length: 50, price: 990, stock: 8, isAvailable: true },
      { _key: 'v1c', label: '60cm - Châtain', color: { name: 'Châtain', hexCode: '#6B3A2A' }, length: 60, price: 1090, stock: 3, isAvailable: true },
    ],
    category: { name: 'Extensions', slug: 'extensions' },
  },
  {
    _id: 'prod-2',
    slug: 'extension-bouclee-sublime',
    name: 'Extension Bouclée Sublime',
    shortDescription: 'Boucles naturelles rebondies et volumineuses',
    basePrice: 950,
    comparePrice: null,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    stockStatus: 'in_stock',
    productType: ['extensions'],
    texture: ['bouclée'],
    rating: 4.9,
    reviewCount: 87,
    variants: [
      { _key: 'v2a', label: '40cm - Noir', color: { name: 'Noir', hexCode: '#1A1410' }, length: 40, price: 950, stock: 20, isAvailable: true },
      { _key: 'v2b', label: '50cm - Brun', color: { name: 'Brun', hexCode: '#3D2B1F' }, length: 50, price: 1050, stock: 5, isAvailable: true },
    ],
    category: { name: 'Extensions', slug: 'extensions' },
  },
  {
    _id: 'prod-3',
    slug: 'perruque-lace-front',
    name: 'Perruque Lace Front Premium',
    shortDescription: 'Perruque lace front ultra-réaliste',
    basePrice: 1450,
    comparePrice: 1800,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    stockStatus: 'in_stock',
    productType: ['perruque'],
    texture: ['lisse'],
    rating: 4.7,
    reviewCount: 203,
    variants: [
      { _key: 'v3a', label: '14 pouces - Noir', color: { name: 'Noir', hexCode: '#1A1410' }, length: 35, price: 1450, stock: 12, isAvailable: true },
      { _key: 'v3b', label: '18 pouces - Noir', color: { name: 'Noir', hexCode: '#1A1410' }, length: 45, price: 1650, stock: 7, isAvailable: true },
    ],
    category: { name: 'Perruques', slug: 'perruques' },
  },
  {
    _id: 'prod-4',
    slug: 'extension-afro-naturelle',
    name: 'Extension Afro Naturelle',
    shortDescription: 'Texture afro authentique, densité naturelle',
    basePrice: 780,
    comparePrice: null,
    isNew: true,
    isBestSeller: false,
    isFeatured: false,
    stockStatus: 'low_stock',
    productType: ['extensions'],
    texture: ['afro'],
    rating: 4.6,
    reviewCount: 56,
    variants: [
      { _key: 'v4a', label: '30cm - Noir', color: { name: 'Noir', hexCode: '#1A1410' }, length: 30, price: 780, stock: 4, isAvailable: true },
    ],
    category: { name: 'Extensions', slug: 'extensions' },
  },
  {
    _id: 'prod-5',
    slug: 'serre-tete-satin',
    name: 'Serre-tête Satin Glowry',
    shortDescription: 'Serre-tête en satin premium pour protéger vos cheveux',
    basePrice: 180,
    comparePrice: null,
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    stockStatus: 'in_stock',
    productType: ['accessoire'],
    texture: [],
    rating: 4.5,
    reviewCount: 34,
    variants: [
      { _key: 'v5a', label: 'Beige', color: { name: 'Beige', hexCode: '#F5EDE0' }, length: 0, price: 180, stock: 50, isAvailable: true },
      { _key: 'v5b', label: 'Noir', color: { name: 'Noir', hexCode: '#1A1410' }, length: 0, price: 180, stock: 50, isAvailable: true },
    ],
    category: { name: 'Accessoires', slug: 'accessoires' },
  },
  {
    _id: 'prod-6',
    slug: 'extension-ondule-naturelle',
    name: 'Extension Ondulée Body Wave',
    shortDescription: 'Ondulations naturelles et brillantes',
    basePrice: 920,
    comparePrice: 1050,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    stockStatus: 'in_stock',
    productType: ['extensions'],
    texture: ['ondulée'],
    rating: 4.8,
    reviewCount: 99,
    variants: [
      { _key: 'v6a', label: '45cm - Noir', color: { name: 'Noir', hexCode: '#1A1410' }, length: 45, price: 920, stock: 18, isAvailable: true },
      { _key: 'v6b', label: '55cm - Brun', color: { name: 'Brun', hexCode: '#3D2B1F' }, length: 55, price: 1020, stock: 6, isAvailable: true },
    ],
    category: { name: 'Extensions', slug: 'extensions' },
  },
];

export const mockCategories = [
  { name: 'Extensions', slug: 'extensions', description: 'Extensions 100% naturelles' },
  { name: 'Perruques', slug: 'perruques', description: 'Perruques premium lace front' },
  { name: 'Accessoires', slug: 'accessoires', description: 'Accessoires cheveux premium' },
];

export const mockBlogPosts = [
  {
    _id: 'post-1',
    slug: 'comment-choisir-ses-extensions',
    title: 'Comment choisir ses extensions selon sa texture naturelle',
    excerpt: 'Guide complet pour trouver les extensions parfaites qui se fondent naturellement avec vos cheveux.',
    featuredImage: null,
    author: { name: 'Équipe Ritual Glowry', image: null },
    categories: ['Guides', 'Entretien'],
    publishedAt: '2026-05-15T10:00:00Z',
    readTime: 7,
    tags: ['extensions', 'guide', 'texture'],
    body: [
      { type: 'paragraph', text: 'Choisir des extensions qui se fondent parfaitement avec vos cheveux naturels est un art. Dans ce guide complet, nous vous expliquons comment sélectionner la texture, la couleur et la longueur idéales.' },
      { type: 'heading', text: 'Comprendre votre texture naturelle' },
      { type: 'paragraph', text: 'Avant tout achat, identifiez votre type de cheveux : lisse (type 1), ondulé (type 2), bouclé (type 3), ou crépu (type 4). Cette classification vous guidera vers les extensions les plus adaptées.' },
      { type: 'tip', text: 'Conseil pro : Prenez une photo de vos cheveux mouillés et secs pour comparer avec nos guides de texture disponibles sur notre site.' },
      { type: 'heading', text: 'La longueur idéale' },
      { type: 'paragraph', text: 'La longueur des extensions dépend de votre longueur naturelle actuelle et de l\'effet désiré. Pour un résultat naturel, ne dépassez pas 20cm de plus que votre longueur actuelle.' },
    ]
  },
  {
    _id: 'post-2',
    slug: 'entretien-extensions-naturelles',
    title: 'Entretien des extensions naturelles : les gestes indispensables',
    excerpt: 'Prolongez la durée de vie de vos extensions avec nos conseils d\'entretien professionnels.',
    featuredImage: null,
    author: { name: 'Équipe Ritual Glowry', image: null },
    categories: ['Entretien', 'Guides'],
    publishedAt: '2026-05-08T10:00:00Z',
    readTime: 5,
    tags: ['entretien', 'cheveux', 'conseils'],
    body: [
      { type: 'paragraph', text: 'Des extensions bien entretenues peuvent durer jusqu\'à 12 mois. Voici les gestes essentiels pour les garder belles et brillantes.' },
      { type: 'heading', text: 'Le lavage' },
      { type: 'paragraph', text: 'Lavez vos extensions avec un shampooing doux, sans sulfates, à l\'eau tiède. Évitez les produits contenant des alcools forts qui assèchent les fibres.' },
    ]
  },
  {
    _id: 'post-3',
    slug: 'tendances-couleurs-2026',
    title: 'Tendances couleurs cheveux 2026 : ce que les stars portent',
    excerpt: 'Du chocolate brown au sandy blonde, découvrez les teintes phares de cette année.',
    featuredImage: null,
    author: { name: 'Équipe Ritual Glowry', image: null },
    categories: ['Tendances', 'Avant/Après'],
    publishedAt: '2026-04-20T10:00:00Z',
    readTime: 4,
    tags: ['tendances', 'couleurs', '2026'],
    body: [
      { type: 'paragraph', text: 'Cette année, les tendances capillaires s\'orientent vers des teintes riches et naturelles. Focus sur les couleurs incontournables de 2026.' },
    ]
  },
  {
    _id: 'post-4',
    slug: 'guide-perruques-lace-front',
    title: 'Tout savoir sur les perruques lace front : guide débutante',
    excerpt: 'Application, entretien, durée de vie... On vous dit tout sur les perruques lace front.',
    featuredImage: null,
    author: { name: 'Équipe Ritual Glowry', image: null },
    categories: ['Tutos', 'Guides'],
    publishedAt: '2026-04-05T10:00:00Z',
    readTime: 9,
    tags: ['perruques', 'lace front', 'guide'],
    body: [
      { type: 'paragraph', text: 'Les perruques lace front révolutionnent le monde de la coiffure. Leur rendu ultra-naturel en fait la solution idéale pour changer de look sans compromis.' },
    ]
  },
]

export type BlogPost = typeof mockBlogPosts[0]
